// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGASmIR9P8ylA3Oia2HSMNa4K80d0xHMk',
    appId: '1:95008435096:web:aaf5b8c78a397b133099ed',
    messagingSenderId: '95008435096',
    projectId: 'zeroappzero-e1b4a',
    authDomain: 'zeroappzero-e1b4a.firebaseapp.com',
    databaseURL: 'https://zeroappzero-e1b4a-default-rtdb.firebaseio.com',
    storageBucket: 'zeroappzero-e1b4a.appspot.com',
    measurementId: 'G-JG150HLC1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGASmIR9P8ylA3Oia2HSMNa4K80d0xHMk',
    appId: '1:95008435096:android:YOUR_ANDROID_APP_ID', // سيتم استبداله لاحقاً
    messagingSenderId: '95008435096',
    projectId: 'zeroappzero-e1b4a',
    storageBucket: 'zeroappzero-e1b4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGASmIR9P8ylA3Oia2HSMNa4K80d0xHMk',
    appId: '1:95008435096:ios:YOUR_IOS_APP_ID', // سيتم استبداله لاحقاً
    messagingSenderId: '95008435096',
    projectId: 'zeroappzero-e1b4a',
    storageBucket: 'zeroappzero-e1b4a.appspot.com',
    iosBundleId: 'com.example.zero', // سيتم استبداله لاحقاً
  );
}
